# Generated by Django 5.0.6 on 2026-07-06 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Circuit breaker switch to suspend services due to non-payment'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='Name of the condominium (e.g., Residencias Los Sauces)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(help_text='Subdomain for routing purposes (e.g., lossauces)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary phone contact information', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Global Platform Admin (Aporte Team)'), ('CONDO_ADMIN', 'Condominium Administrator (Board/Management Co.)'), ('RESIDENT', 'Resident / Coproprietary')], default='RESIDENT', help_text='Hierarchical security role within the platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Condominium cluster the user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='BoardBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(help_text='Official bank entity name (e.g., Banesco, Banco de Venezuela)', max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='The full 20-digit standard Venezuelan bank account number', max_length=20, null=True)),
                ('pago_movil_phone', models.CharField(blank=True, help_text='The telephone number linked to the Pago Móvil channel', max_length=30, null=True)),
                ('pago_movil_id', models.CharField(blank=True, help_text='The fiscal ID (Cédula or RIF) bound to the Pago Móvil registry', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Status flag to enable or disable this account for resident visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='The condominium complex that owns this financial account', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number', models.CharField(help_text='The apartment or house number (e.g., Apt 4B, House 12)', max_length=20)),
                ('floor', models.CharField(blank=True, help_text='The building floor where the unit is located (if applicable)', max_length=10, null=True)),
                ('block_or_tower', models.CharField(blank=True, help_text='Tower or section indicator (e.g., Tower A, Phase II)', max_length=50, null=True)),
                ('aliquot', models.DecimalField(decimal_places=4, help_text="The property's participation percentage in general expenses (e.g., 0.0250 for 2.5%)", max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The primary user registered as the legal owner of this unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The condominium complex this unit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'unique_together': {('tenant', 'unit_number', 'block_or_tower')},
            },
        ),
    ]
